name: Update Twitter Section

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
      - name: Check for new tweets
        run: python tweet.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Blake Sanie'
          git config --global user.email 'blakesanie@users.noreply.github.com'
          git commit -am "Automated update"
          git push
